title: Lloyds Climate Memorial
description:
tagline:

# Theme colours
background_color: "#FFF0E3"
brand_color: "#DD0000"
accent_color: "#DD0000"

permalink: pretty

airtable:
  images:
    app: appPjgDjZYloVPKvw
    table: tblxcxR5AIWrFIHKy
    view: viwpmRi657GTVzwz9

plugins:
  - jekyll-airtable-import
